server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TomaEduard/microservices-config-store-rent-a-car
          search-paths:
            - 'service-config/*service'
#          username:
#          passphrase:
