server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TomaEduard/spring-cloud-config-store
          search-paths:
            - '*service'
#          username:
#          passphrase:
